//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCD1_TranMinhDuc_2210900014.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmd_News
    {
        public int MaNew { get; set; }
        public string TitleNew { get; set; }
        public string Mota1 { get; set; }
        public string Mota2 { get; set; }
        public string Anh { get; set; }
    }
}
