//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCD1_TranMinhDuc_2210900014.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmd_Quantri
    {
        public int MaAdmin { get; set; }
        public string HotenAdmin { get; set; }
        public string MatkhauAdmin { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string Taikhoan { get; set; }
    }
}
