//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCD1_TranMinhDuc_2210900014.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tmd_2210900014_TTCDEntities : DbContext
    {
        public Tmd_2210900014_TTCDEntities()
            : base("name=Tmd_2210900014_TTCDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tmd_HoaDon> Tmd_HoaDon { get; set; }
        public virtual DbSet<Tmd_KhachHang> Tmd_KhachHang { get; set; }
        public virtual DbSet<Tmd_News> Tmd_News { get; set; }
        public virtual DbSet<Tmd_NSX> Tmd_NSX { get; set; }
        public virtual DbSet<Tmd_Quantri> Tmd_Quantri { get; set; }
        public virtual DbSet<Tmd_SanPham> Tmd_SanPham { get; set; }
    }
}
