//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCD1_TranMinhDuc_2210900014.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmd_NSX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tmd_NSX()
        {
            this.Tmd_SanPham = new HashSet<Tmd_SanPham>();
        }
    
        public string MaNSX { get; set; }
        public string TenNSX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tmd_SanPham> Tmd_SanPham { get; set; }
    }
}
